 SESSION  SET  GRAPH  (  DURATION_BETWEEN  (  DURATION_BETWEEN  (  CURRENT_TIME  ,  LOCAL_TIMESTAMP  )  YEAR  TO  MONTH  +  CURRENT_TIME  -  COUNT  (  *  )  -  COUNT  (  *  )  ,  CURRENT_TIMESTAMP  )  ) 