 SESSION  SET  VALUE  $b =  DURATION_BETWEEN  (  DURATION_BETWEEN  (  CURRENT_TIMESTAMP  ,  CURRENT_DATE  )  +  LOCAL_TIMESTAMP  -  COUNT  (  *  )  -  SESSION_USER  -  COUNT  (  *  )  ,  LOCAL_TIMESTAMP  ) 