 SESSION  SET  VALUE  $b =  DURATION_BETWEEN  (  DURATION_BETWEEN  (  CURRENT_TIMESTAMP  ,  CURRENT_TIME  )  +  CURRENT_DATE  +  COUNT  (  *  )  -  COUNT  (  *  )  - b +  COUNT  (  *  )  ,  CURRENT_TIME  ) 