 SESSION  SET  GRAPH  (  DURATION_BETWEEN  (  DURATION_BETWEEN  (  CURRENT_TIMESTAMP  ,  LOCAL_TIMESTAMP  )  +  LOCAL_TIMESTAMP  +  COUNT  (  *  )  + a + c -  SESSION_USER  ,  CURRENT_TIMESTAMP  )  ) 